# 应用程序名称
spring:
  application:
    name: RapidDataChat-backend
  datasource:
    url: jdbc:postgresql://pgvector:5432/RapidDataChat_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

    # PostgreSQL数据库配置优化
    hikari:
      maximum-pool-size: 20  # Hikari连接池的最大连接数
      minimum-idle: 10  # Hikari连接池的最小空闲连接数
      idle-timeout: 30000  # 空闲连接超时时间，单位为毫秒
      connection-timeout: 30000  # 获取连接的超时时间，单位为毫秒
      max-lifetime: 1800000  # 连接的最大生命周期，单位为毫秒

  jackson:
    serialization:
      fail-on-empty-beans: false  # 序列化空对象时不失败

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration  # 禁用MongoDB自动配置

  thymeleaf:
    cache: false  # 禁用Thymeleaf模板缓存

  devtools:
    restart:
      enabled: true  # 启用Spring DevTools自动重启功能

server:
  port: 8080  # 服务器端口号
  error:
    include-message: always  # 错误信息包含在响应中
    include-binding-errors: always  # 绑定错误信息包含在响应中
  tomcat:
    accept-count: 100  # Tomcat连接请求队列的最大长度
    connection-timeout: 20000  # Tomcat连接超时时间，单位为毫秒
  servlet:
    session:
      timeout: 30m  # 会话超时时间，单位为分钟
      persistent: true  # 会话是否持久化

logging:
  level:
    org:
      springframework:
        web: INFO  # Spring Web模块的日志级别
    com:
      RapidDataChat:
        backend: DEBUG  # 应用程序后端的日志级别

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI路径
  show-actuator: true  # 显示Actuator端点

# 自定义配置
embedding:
  api:
    url: http://xinference:9997/v1/embeddings  # 嵌入API的URL

mybatis-plus:
  type-handlers-package: com.RapidDataChat.backend.typehandler  # MyBatis Plus类型处理器包路径
